server:
  port: 8081
  data:
    mongodb:
      database: devops
      host: localhost
      port: 27017

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG