server:
  port: 8088

logging:
  level:
    root: INFO
    org.springframework.web: trace
    org.springframework.security: trace
    org.springframework.security.oauth2: trace

spring:
  security:
    oauth2:
      client:
        registration:
          client-oidc:
            client-id: client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - read
              - profile
            client-name: client-oidc
            provider: auth-server
        provider:
          auth-server:
            issuer-uri: http://auth-server:9000
#            authorization-uri: http://auth-server:9000/oauth2/authorize
#            token-uri: http://auth-server:9000/oauth2/token
